appid = 0
platform = kuber

appname = GIDS
httpport = 9090
httpsport = {tls_port}
runmode = dev
copyrequestbody = true

logfile=/dev/out
loglevel=INFO

[gaussdb]
databasepassword=Cspdbg@2017
gaussdbport=23521
gaussdbuser=sbggidsdbuser
gaussdbdbname=sbggidsdb
servicename=SbgGaussDB

[moon]
configEndpoint={config_url}
titokEndpoint={tiktok_endpoint}
httpsConfigEndpoint={httpsconfig_url}
httpsTitokEndpoint={httpstiktok_endpoint}
httpport={port}

[cspmonitor]
monitorJsonFile=/opt/csp/gids/module/conf/monitor.json
sqlYamlFile=/opt/csp/gids/module/conf/sql.yaml

[redis]
endpoint=135.242.67.210:6379

[node]
endpoint=135.242.67.210:9090
httpsendpoint=41.203.73.2:40051

[oss]
endpoint=135.242.67.210:9000

[local]
sqlitepath = ./data/gids.db